export interface PackageDetails {
  contributions_count: number;
  dependent_repos_count: number;
  dependents_count: number;
  deprecation_reason: string | null;
  description: string | null;
  forks: number;
  homepage: string | null;
  keywords: string[];
  language: string | null;
  latest_download_url: string | null;
  latest_release_number: string | null;
  latest_release_published_at: string | null;
  latest_stable_release_number: string | null;
  latest_stable_release_published_at: string | null;
  liscense_normalized: string | null;
  liscenses: string[] | string | null;
  name: string | null;
  normalized_licenses: string[] | string | null;
  package_manager_url: string | null;
  platform: string | null;
  rank: number | null;
  repository_liscense: string | null;
  repository_status: string | null;
  repository_url: string | null;
  stars: number;
  status: string | null;
  versions: {
    number: string;
    published_at: string;
    spdx_expression: string;
    original_license: string;
    researched_at: string | null;
    repository_resources: string[];
  }[]
}

export interface GHRepoDetails {
  id: number;
  node_id: string;
  private: boolean;
  archived: boolean;
  created_at: string;
  default_branch: string;
  description: string;
  fork: boolean;
  forks_count: number;
  full_name: string;
  homepage: string;
  html_url: string;
  language: string;
  license: {
    key: string;
    name: string;
    spdx_id: string;
    url: string;
  } | null;
  name: string;
  open_issues_count: number;
  owner: {
    id: number;
    node_id: string;
    avatar_url: string;
    gravatar_id: string;
    html_url: string;
    followers_url: string;
    following_url: string;
    gists_url: string;
    starred_url: string;
    subscriptions_url: string;
    organizations_url: string;
    repos_url: string;
    events_url: string;
    received_events_url: string;
    site_admin: boolean;
    login: string;
    type: string;
    url: string;
  };
  url: string;
  forks_url: string;
  keys_url: string;
  collaborators_url: string;
  teams_url: string;
  hooks_url: string;
  issue_events_url: string;
  events_url: string;
  assignees_url: string;
  branches_url: string;
  tags_url: string;
  blobs_url: string;
  git_tags_url: string;
  git_refs_url: string;
  trees_url: string;
  statuses_url: string;
  languages_url: string;
  stargazers_url: string;
  contributors_url: string;
  subscribers_url: string;
  subscription_url: string;
  commits_url: string;
  git_commits_url: string;
  comments_url: string;
  issue_comment_url: string;
  contents_url: string;
  compare_url: string;
  merges_url: string;
  archive_url: string;
  downloads_url: string;
  issues_url: string;
  pulls_url: string;
  milestones_url: string;
  notifications_url: string;
  labels_url: string;
  releases_url: string;
  deployments_url: string;
  git_url: string;
  ssh_url: string;
  clone_url: string;
  svn_url: string;
  homepage_url: string;
  pushed_at: string;
  size: number;
  stargazers_count: number;
  updated_at: string;
  watchers_count: number;
  has_issues: boolean;
  has_projects: boolean;
  has_downloads: boolean;
  has_wiki: boolean;
  has_pages: boolean;
  has_discussions: boolean;
  mirror_url: string | null;
  disabled: boolean;
  allow_forking: boolean;
  is_template: boolean;
  web_commit_signoff_required: boolean;
  topics: string[];
  visibility: string;
  forks: number;
  open_issues: number;
  watchers: number;
  temp_clone_token: string | null;
  organization: {
    login: string;
    id: number;
    node_id: string;
    url: string;
    html_url: string;
    followers_url: string;
    following_url: string;
    gists_url: string;
    starred_url: string;
    subscriptions_url: string;
    organizations_url: string;
    repos_url: string;
    events_url: string;
    hooks_url: string;
    issues_url: string;
    members_url: string;
    public_members_url: string;
    avatar_url: string;
    description: string;
  } | null;
  network_count: number;
  subscribers_count: number;
}

export type CombinedPackageDetails = PackageDetails & GHRepoDetails;